//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNMutableContact.h"

@interface CNMutableContact (PhoneAdditions)
+ (id)mutableUnknownContactWithDestinationID:(id)arg1 countryCode:(id)arg2;
+ (id)mutableUnknownContactWithDestinationID:(id)arg1 countryCode:(id)arg2 useSuggestedContact:(BOOL)arg3;
+ (id)mutableUnknownContactWithRecentCall:(id)arg1;
@end

