//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface CommunicationDisplayViewController : UIViewController
{
}

+ (BOOL)shouldRelock;
+ (BOOL)starkUnlocked;
+ (BOOL)lockWasInterrupted;
+ (BOOL)springBoardIsLocked;
- (void)_postOkToRelock;
- (BOOL)_shouldRelock;
- (BOOL)isShowingLock;
- (BOOL)_springboardIsLocked;
- (BOOL)_lockWasInterrupted;

@end

