//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneViewController.h"

#import "DialerViewDelegate.h"
#import "TPDialerKeypadDelegate.h"
#import "UIActionSheetDelegate.h"

@class NSString, NSTimer, PHAbstractDialerView;

@interface DialerController : PhoneViewController <DialerViewDelegate, UIActionSheetDelegate, TPDialerKeypadDelegate>
{
    PHAbstractDialerView *_dialerView;
    NSTimer *_deleteTimer;
    NSTimer *_lookupTimer;
    NSString *_lastDialedNumberCache;
    NSString *_myPrefix;
    int _shouldUseMyPrefixAsHint;
    unsigned int _calledNumber:1;
    unsigned int _didDeleteRepeat:1;
    unsigned int _loadedLastDialedNumberCache:1;
    unsigned int _dtmfPlaying;
    BOOL _shouldHideDeleteButtonWhenEmpty;
    int _dialerType;
}

+ (id)defaultPNGName;
+ (id)tabBarIconName;
+ (id)tabBarIconImageSelected;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageName;
+ (int)tabViewType;
+ (BOOL)launchFieldTestIfNeeded:(id)arg1;
+ (BOOL)shouldStringAutoDial:(id)arg1 givenLastChar:(BOOL)arg2;
+ (void)stopPlayingDTMFTone;
+ (void)playDTMFToneForKey:(unsigned char)arg1;
@property int dialerType; // @synthesize dialerType=_dialerType;
@property(nonatomic) BOOL shouldHideDeleteButtonWhenEmpty; // @synthesize shouldHideDeleteButtonWhenEmpty=_shouldHideDeleteButtonWhenEmpty;
@property(readonly) PHAbstractDialerView *dialerView; // @synthesize dialerView=_dialerView;
- (void).cxx_destruct;
- (void)updateBackgroundAnimated:(BOOL)arg1;
- (void *)sharedAddressBook;
- (BOOL)defaultActionIsFaceTimeAudio;
- (int)addressBookStyle;
- (void)_applicationWillResignActiveNotification:(id)arg1;
- (void)_statusBarHeightChanged:(id)arg1;
- (void)_handleSIMInsertionOrRemoval;
- (void)performDeleteAction;
- (void)performCallActionForService:(int)arg1;
- (void)restoreLastDialedNumber;
- (BOOL)digitsEntered;
- (void)_deleteButtonDown:(id)arg1;
- (void)_deleteButtonClicked:(id)arg1;
- (void)_stopDeleteTimer;
- (void)_startDeleteTimer;
- (void)_deleteRepeat;
- (void)_addButtonClicked:(id)arg1;
- (id)_qualifyNumberIfNecessary:(id)arg1;
- (void)_dialVoicemail;
- (void)phonePad:(id)arg1 keyUp:(BOOL)arg2;
- (void)phonePad:(id)arg1 keyDown:(BOOL)arg2;
- (void)phonePadDidEndSounds:(id)arg1;
- (id)_myPrefix;
- (BOOL)_shouldUseMyPrefixAsHint;
- (void)phonePadDeleteLastDigit:(id)arg1;
- (void)phonePad:(id)arg1 replaceLastDigitWithString:(id)arg2;
- (void)_phonePad:(id)arg1 appendString:(id)arg2 suppressClearingDialedNumber:(BOOL)arg3;
- (void)phonePad:(id)arg1 appendString:(id)arg2 playDTMFTone:(BOOL)arg3;
- (void)phonePad:(id)arg1 appendString:(id)arg2;
- (void)performCharacterAddAction:(id)arg1;
- (void)phonePad:(id)arg1 dialerCharacterButtonWasHeld:(unsigned int)arg2;
- (void)_callButtonPressed:(id)arg1;
- (void)_updateName;
- (void)_animateCallButton;
- (void)_fadeSubviewsOf:(id)arg1 excludingView:(id)arg2 toValue:(float)arg3;
- (void)_callButtonLongPress;
- (void)_updateCallButtonEnabledState:(id)arg1;
- (void)_updateLCDNameLabelWithOriginallyPastedString:(id)arg1;
- (void)_updateLCDNameLabelWithAMatchingName:(BOOL)arg1;
- (void)_updateCallButtonEnabledState:(id)arg1 updateNameNow:(BOOL)arg2;
- (id)pseudoNameStringForDestinationID:(id)arg1;
- (void)dialerView:(id)arg1 stringWasPasted:(id)arg2;
- (void)dialerViewTextDidChange:(id)arg1;
- (void)showOrHideDeleteButton;
@property(retain) NSString *lastDialedNumber;
- (void)_getPersonName:(id *)arg1 personLabel:(id *)arg2 personUID:(int *)arg3 forPhoneNumberString:(id)arg4;
- (void)_stopLookupTimer;
- (BOOL)shouldSnapshot;
- (void)prepareForSnapshot;
- (void)_clearDisplayIfNecessary;
- (void)dealloc;
- (id)initWithDialerType:(int)arg1;
- (void)_callStatusChanged:(id)arg1;
- (void)_resetButtonAnimation;
- (void)applicationDidResume;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)shouldAnimateCallButton;
- (BOOL)isShowingDoubleHeightStatusBar;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

