//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneApplication.h"

@interface MobilePhoneApplication : PhoneApplication
{
}

- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (BOOL)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)applicationDidBecomeActive:(id)arg1;
- (int)headerViewNumberOfCallsToShow;
- (BOOL)headerViewShowsAllRecentCalls;
- (BOOL)audioButtonAllowsPhoneCallsAndFaceTimeAudio;
- (BOOL)hasEnhancedVoicemail;
- (BOOL)shouldHideVoicemailUI;
- (BOOL)showsPhoneVoicemail;
- (BOOL)showsPhoneDialer;
- (BOOL)badgesMissedFaceTimeVideo;
- (BOOL)badgesMissedFaceTimeAudio;
- (BOOL)badgesMissedTelephonyCalls;
- (BOOL)showsFaceTimeVideoRecents;
- (BOOL)showsFaceTimeAudioRecents;
- (BOOL)showsTelephonyRecents;
- (BOOL)showsFaceTimeVideoFavorites;
- (BOOL)showsFaceTimeAudioFavorites;
- (BOOL)showsTelephonyFavorites;
- (BOOL)showsFaceTimeAudio;
- (BOOL)showsFaceTimeVideo;
- (BOOL)showsTelephonyCalls;
- (int)defaultAction;
- (BOOL)showSplashScreenOnSignin;
- (BOOL)tabBarCanSlide;
- (BOOL)tabBarFillsScreen;
- (BOOL)contentViewCanRotate;
- (BOOL)alwaysShowLocalVideo;
- (BOOL)usesBlendModes;
- (int)contactsViewControllerStyle;
- (int)addressBookUIStyle;
- (int)wizardGlobalAppearanceStyle;
- (unsigned int)userInterfaceStyle;
- (void)dealloc;
- (id)init;
- (void)applicationDidFinishLaunching:(id)arg1;
- (BOOL)_isIPad;

@end

