//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface PHAudioDeviceController : NSObject
{
    NSDictionary *_pickedRoute;
}

+ (id)sharedAudioDeviceController;
@property(readonly, nonatomic) NSDictionary *pickedRoute; // @synthesize pickedRoute=_pickedRoute;
- (void).cxx_destruct;
- (void)_registerForAVSystemControllerNotifications;
- (void)_pickableRoutesChanged;
- (void)_mediaServerDied;
- (BOOL)_routeIsHandset:(id)arg1;
- (BOOL)_routeIsDefault:(id)arg1;
- (BOOL)_routeIsReceiver:(id)arg1;
- (BOOL)_routeIsSpeaker:(id)arg1;
- (BOOL)_routeIsWirelessHeadset:(id)arg1;
- (BOOL)_routeIsAirTunes:(id)arg1;
- (BOOL)_routeIsAirPlayMirroring:(id)arg1;
- (BOOL)_routeIsBlueToothLEA:(id)arg1;
- (BOOL)isAirPlayMirroring;
- (void)_pickRoute:(id)arg1;
- (id)_pickableRoutes;
- (id)_pickedRoute;
- (BOOL)pickRouteByName:(id)arg1;
- (void)pickRouteAtIndex:(unsigned int)arg1;
- (void)_enumerateRoutes:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateRoutesWithCategory:(id)arg1 mode:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)enumerateRoutesUsingBlock:(CDUnknownBlockType)arg1;
- (id)routeNameAtIndex:(unsigned int)arg1 isPicked:(char *)arg2;
- (id)routeTypeAtIndex:(unsigned int)arg1;
- (BOOL)audioCategoryIsTTY;
- (BOOL)receiverRouteIsPicked;
- (BOOL)speakerRouteIsPicked;
- (void)clearCachedRoutes;
- (void)restorePickedRoute;
- (BOOL)pickRouteWithUID:(id)arg1;
- (BOOL)pickDefaultRoute;
- (BOOL)pickHandsetRoute;
- (BOOL)pickSpeakerRoute;
- (BOOL)handsetRouteAvailable;
- (BOOL)speakerRouteAvailable;
- (int)numberOfAudioRoutes;
- (BOOL)auxiliaryAudioRoutesAvailable;
@property(readonly, nonatomic) NSString *pickedRouteUID;
- (void)dealloc;
- (id)init;

@end

