//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CHManager, NSArray, NSObject<OS_dispatch_queue>, NSString;

@interface PHCallHistoryController : NSObject
{
    unsigned int _callTypes;
    NSString *_coalescingStrategy;
    unsigned int _options;
    NSArray *_recentCalls;
    unsigned int _unreadCallCount;
    CHManager *_callHistoryManager;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

+ (id)callHistoryControllerWithCoalescingStrategy:(id)arg1 options:(unsigned int)arg2;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) CHManager *callHistoryManager; // @synthesize callHistoryManager=_callHistoryManager;
@property(nonatomic) unsigned int unreadCallCount; // @synthesize unreadCallCount=_unreadCallCount;
@property(retain, nonatomic) NSArray *recentCalls; // @synthesize recentCalls=_recentCalls;
- (void).cxx_destruct;
- (void)callHistoryDatabaseChanged:(id)arg1;
- (CDUnknownBlockType)qosUserInteractiveDispatchBlockForBlock:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)callHistoryManagerRecentCallsDispatchBlock;
- (CDUnknownBlockType)callHistoryManagerInitializationDispatchBlock;
- (CDUnknownBlockType)callHistoryControllerDidInitializeBlock;
- (id)recentCallsWithPredicate:(id)arg1;
- (void)markRecentCallsAsReadWithPredicate:(id)arg1;
- (void)markRecentCallsAsRead;
- (void)deleteRecentCalls:(id)arg1;
- (void)deleteRecentCall:(id)arg1;
- (void)deleteAllRecentCalls;
- (void)boost;
@property(nonatomic) unsigned int options; // @synthesize options=_options;
@property(copy, nonatomic) NSString *coalescingStrategy; // @synthesize coalescingStrategy=_coalescingStrategy;
@property(nonatomic) unsigned int callTypes; // @synthesize callTypes=_callTypes;
- (void)loadDispatchQueue;
- (void)dealloc;
- (id)initWithCoalescingStrategy:(id)arg1 options:(unsigned int)arg2;
- (id)init;

@end

