//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNContactNavigationController.h"

#import "CNContactNavigationControllerDelegate.h"
#import "PhoneTabViewController.h"

@class CNContact, NSString;

@interface PHContactsViewController : CNContactNavigationController <CNContactNavigationControllerDelegate, PhoneTabViewController>
{
    BOOL _disableContactsWithoutHandles;
    BOOL _shouldFetchTelephoneNumber;
    id <PHContactsControllerDelegate> _contactsControllerDelegate;
    int _style;
    NSString *_telephoneNumber;
}

+ (id)defaultPNGName;
+ (id)tabBarIconName;
+ (CDStruct_f8b960e9)badge;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
@property(copy, nonatomic) NSString *telephoneNumber; // @synthesize telephoneNumber=_telephoneNumber;
@property(nonatomic) BOOL shouldFetchTelephoneNumber; // @synthesize shouldFetchTelephoneNumber=_shouldFetchTelephoneNumber;
@property int style; // @synthesize style=_style;
@property(nonatomic) id <PHContactsControllerDelegate> contactsControllerDelegate; // @synthesize contactsControllerDelegate=_contactsControllerDelegate;
@property(nonatomic) BOOL disableContactsWithoutHandles; // @synthesize disableContactsWithoutHandles=_disableContactsWithoutHandles;
- (void).cxx_destruct;
- (void)_restoreState;
@property(retain) CNContact *savedPerson;
@property(readonly) BOOL shouldSaveAndRestoreState;
- (void)phoneApplicationPreferencesChanged:(id)arg1;
- (void)removeNotificationObservers;
- (void)addNotificationObservers;
- (void)fetchTelephoneNumber;
- (void)fetchPreferences;
- (BOOL)contactNavigationController:(id)arg1 canSelectContact:(id)arg2;
- (BOOL)contactNavigationController:(id)arg1 shouldPerformDefaultActionForContactProperty:(id)arg2;
- (BOOL)contactNavigationController:(id)arg1 shouldShowCardForContact:(id)arg2;
- (void)contactNavigationControllerDidCancel:(id)arg1;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)tabBarControllerShouldSelectViewController:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

