//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DialerController.h"

#import "CNContactPickerDelegate.h"
#import "CNContactViewControllerDelegate.h"
#import "UIAlertControllerSystemProvidedPresentationDelegate.h"

@class NSString, PHDialerAlertController;

@interface PHDialerViewController : DialerController <CNContactPickerDelegate, CNContactViewControllerDelegate, UIAlertControllerSystemProvidedPresentationDelegate>
{
    PHDialerAlertController *_callTypeAlertController;
}

@property(retain, nonatomic) PHDialerAlertController *callTypeAlertController; // @synthesize callTypeAlertController=_callTypeAlertController;
- (void).cxx_destruct;
- (void)_willBeginSystemProvidedPresentationOfAlertController:(id)arg1;
- (id)_presentingViewControllerForSystemProvidedPresentationOfAlertController:(id)arg1;
- (BOOL)_shouldPerformSystemProvidedPresentationOfAlertController:(id)arg1 atSystemProvidedPresentationRegisteredViewLocation:(struct CGPoint)arg2;
- (void)_updateAction:(id)arg1 forService:(id)arg2 withDestination:(id)arg3;
- (id)pseudoNameStringForDestinationID:(id)arg1;
- (BOOL)defaultActionIsFaceTimeAudio;
- (int)addressBookStyle;
- (void)updateBackgroundAnimated:(BOOL)arg1;
- (void)didReceiveMemoryWarning;
- (void)unloadView;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)contactViewWrapperDidCancel;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (id)_newContactWithPhoneNumber:(id)arg1;
- (void)_addNewContact:(id)arg1;
- (void)_updateName;
- (void)_metadataCacheDidUpdate:(id)arg1;
- (id)_metadataNameForDialerText;
- (void)_addButtonClicked:(id)arg1;
- (BOOL)_anyContactsExist;
- (void)viewDidLoad;
- (id)initWithDialerType:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

