//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneViewController.h"

#import "CNContactPickerDelegate.h"
#import "CNContactViewControllerDelegate.h"
#import "PHFavoritesCellDelegateProtocol.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CNFavoritesEntry, NSString, UITableView, _UIContentUnavailableView;

@interface PHFavoritesViewController : PhoneViewController <UITableViewDataSource, UITableViewDelegate, PHFavoritesCellDelegateProtocol, CNContactViewControllerDelegate, CNContactPickerDelegate>
{
    UITableView *_table;
    _UIContentUnavailableView *_noContentView;
    CNFavoritesEntry *_selectedFavoritesEntry;
    unsigned int _ignoreFavoritesDidChangeNotification:1;
    unsigned int _postponeTableReloadFromFavoritesChange:1;
    unsigned int _needsTableReloadFromFavoritesChange:1;
}

+ (id)tabBarIconName;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
+ (BOOL)requiresNavigationControllerContainer;
- (void).cxx_destruct;
- (id)presentingViewControllerForAvatarView;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)accessoryButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)deleteButtonPressedForIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)selectedIndex;
- (int)absoluteIndexOfFilteredIndex:(int)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)_addButtonClicked:(id)arg1;
- (id)_predicateForEnablingContact;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)_addEntryFromPeoplePickerForContact:(id)arg1 key:(id)arg2 identifier:(id)arg3 favoritesEntryType:(int)arg4;
- (void)showCardViewerForContact:(id)arg1 withTitle:(id)arg2 animate:(BOOL)arg3;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateNavButtons;
- (void)_favoritesManagerSignificantChangeNotification:(id)arg1;
- (void)restoreState;
- (BOOL)shouldSnapshot;
- (void)unloadView;
- (void)didReceiveMemoryWarning;
- (void)savePreferences;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)_updateContentView;
@property(readonly) _UIContentUnavailableView *noContentView;
- (BOOL)showsNoContentView;
@property(readonly) UITableView *table;
- (void)contentSizeCategoryDidChange;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

