//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "CNAvatarViewDelegate.h"

@class CNAvatarView, CNFavoritesEntry, NSLayoutConstraint, NSMutableArray, NSString, UIImageView, UILabel;

@interface PHFavoritesCell : UITableViewCell <CNAvatarViewDelegate>
{
    UILabel *_titleTextLabel;
    UILabel *_labelTextLabel;
    UIImageView *_iconGlyphView;
    CNAvatarView *_contactPhotoView;
    NSLayoutConstraint *_bottomMarginConstraint;
    NSLayoutConstraint *_iconLabelConstraint;
    long _buildConstraintsOnceToken;
    NSMutableArray *_contactPhotoConstraints;
    NSMutableArray *_textLabelConstraints;
    NSMutableArray *_iconGlyphConstraints;
    CNFavoritesEntry *_favoritesEntry;
    id <PHFavoritesCellDelegateProtocol> _delegate;
}

+ (id)faceTimeAudioGlyphPress;
+ (id)faceTimeAudioGlyph;
+ (id)faceTimeGlyphPress;
+ (id)faceTimeGlyph;
+ (float)editingMarginWidth;
+ (float)marginWidth;
@property(nonatomic) id <PHFavoritesCellDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CNFavoritesEntry *favoritesEntry; // @synthesize favoritesEntry=_favoritesEntry;
- (void).cxx_destruct;
- (id)presentingViewControllerForAvatarView:(id)arg1;
- (void)_updateFonts;
- (BOOL)_drawsTopSeparatorDuringReordering;
- (void)_setReordering:(BOOL)arg1;
- (void)_populateSubviewsFromFavoritesItem;
@property(readonly) BOOL shouldShowIconGlyph;
@property(readonly) BOOL shouldShowTextLabel;
- (void)_handleContentSizeCategoryDidChange:(id)arg1;
- (void)_handleFavoritesEntryChanged:(id)arg1;
- (void)_updateConstraints;
- (void)_buildConstraints;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

