//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "DialerLCDFieldProtocol.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSLayoutConstraint, NSString, PHHandsetDialerNameLabelView, UIButton, UILabel, UILongPressGestureRecognizer;

@interface PHHandsetDialerLCDView : UIView <DialerLCDFieldProtocol, UIGestureRecognizerDelegate>
{
    BOOL _addContactButtonVisible;
    BOOL _deleteButtonVisible;
    BOOL _highlighted;
    BOOL _inCallMode;
    int _dialerType;
    UIButton *_deleteButton;
    UIButton *_addContactButton;
    id <DialerLCDFieldDelegate> _delegate;
    PHHandsetDialerNameLabelView *_nameAndLabelView;
    UILabel *_numberLabel;
    NSString *_unformattedText;
    UILongPressGestureRecognizer *_longPressRecognizer;
    NSLayoutConstraint *_numberLabelVerticalConstraint;
    NSLayoutConstraint *_nameAndLabelViewConstraint;
    NSArray *_numberLabelHorizontalConstraints;
}

@property(retain) NSArray *numberLabelHorizontalConstraints; // @synthesize numberLabelHorizontalConstraints=_numberLabelHorizontalConstraints;
@property(retain) NSLayoutConstraint *nameAndLabelViewConstraint; // @synthesize nameAndLabelViewConstraint=_nameAndLabelViewConstraint;
@property(retain) NSLayoutConstraint *numberLabelVerticalConstraint; // @synthesize numberLabelVerticalConstraint=_numberLabelVerticalConstraint;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain) NSString *unformattedText; // @synthesize unformattedText=_unformattedText;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(retain) PHHandsetDialerNameLabelView *nameAndLabelView; // @synthesize nameAndLabelView=_nameAndLabelView;
@property(nonatomic) BOOL inCallMode; // @synthesize inCallMode=_inCallMode;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) id <DialerLCDFieldDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) UIButton *addContactButton; // @synthesize addContactButton=_addContactButton;
@property(retain) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) int dialerType; // @synthesize dialerType=_dialerType;
- (void).cxx_destruct;
- (void)updateNumberLabelHorizontalConstraints;
- (void)applyLayoutConstraints;
- (id)newAddContactButton;
- (id)newDeleteButton;
- (id)newNameAndLabelView;
- (id)lcdColor;
- (void)handleLongPress:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)resignFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)_displayCallout;
- (void)_menuDidHide:(id)arg1;
- (void)_menuWillHide:(id)arg1;
- (void)_requestMakeCutCopyPasteCalloutVisible:(BOOL)arg1;
- (void)_makeCalloutVisible:(BOOL)arg1;
- (void)_setHighlighted:(BOOL)arg1;
- (void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 suggestion:(BOOL)arg3 animated:(BOOL)arg4;
- (void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 animated:(BOOL)arg3;
- (void)setName:(id)arg1 numberLabel:(id)arg2 suggestion:(BOOL)arg3;
- (void)setName:(id)arg1 numberLabel:(id)arg2;
- (void)deleteCharacter;
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2;
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2 name:(id)arg3 label:(id)arg4;
- (id)text;
- (void)dealloc;
- (struct CGSize)intrinsicContentSize;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 forDialerType:(int)arg2;
- (id)generateNumberLabelHorizontalConstraints;
- (float)deleteButtonYOffset;
- (float)addContactButtonYOffset;
- (float)deleteButtonRightPadding;
- (float)addContactButtonLeftPadding;
- (float)nameAndLabelFontSize;
- (id)numberLabelFont;
- (float)spacingBetweenNumberBaseLineAndNameTop;
- (float)numberLabelMinimumFontSize;
- (float)numberLabelMaximumFontSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

