//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, UILabel;

@interface PHHandsetDialerNameLabelView : UIControl
{
    UILabel *_nameAndLabelLabel;
    float _fontSize;
    NSString *_displayedName;
    NSString *_displayedLabel;
}

@property(retain) NSString *displayedLabel; // @synthesize displayedLabel=_displayedLabel;
@property(retain) NSString *displayedName; // @synthesize displayedName=_displayedName;
@property(nonatomic) float fontSize; // @synthesize fontSize=_fontSize;
@property(retain) UILabel *nameAndLabelLabel; // @synthesize nameAndLabelLabel=_nameAndLabelLabel;
- (void).cxx_destruct;
- (void)showName:(id)arg1 label:(id)arg2 animated:(BOOL)arg3;
- (void)setHighlighted:(BOOL)arg1;
- (struct CGSize)intrinsicContentSize;
- (id)textColor;
- (id)initWithFrame:(struct CGRect)arg1;

@end

