//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PHLocalVideoDisabledOverlayView, UIControl, UIView;

@interface PHLocalVideoViewController : UIViewController
{
    BOOL _localVideoAlwaysMatchesScreen;
    BOOL _supportsAutoRotation;
    BOOL _showsLocalPreviewStatusBarGradient;
    BOOL _waitingForLocalVideoFirstFrame;
    UIControl *_videoGroupView;
    UIView *_localVideoView;
    UIView *_localVideoStatusBarGradientView;
    PHLocalVideoDisabledOverlayView *_disabledOverlayView;
    int _lastKnownOrientation;
}

+ (BOOL)_shouldForwardViewWillTransitionToSize;
@property(nonatomic) int lastKnownOrientation; // @synthesize lastKnownOrientation=_lastKnownOrientation;
@property(nonatomic) BOOL waitingForLocalVideoFirstFrame; // @synthesize waitingForLocalVideoFirstFrame=_waitingForLocalVideoFirstFrame;
@property(nonatomic) BOOL showsLocalPreviewStatusBarGradient; // @synthesize showsLocalPreviewStatusBarGradient=_showsLocalPreviewStatusBarGradient;
@property(nonatomic) BOOL supportsAutoRotation; // @synthesize supportsAutoRotation=_supportsAutoRotation;
@property(nonatomic) BOOL localVideoAlwaysMatchesScreen; // @synthesize localVideoAlwaysMatchesScreen=_localVideoAlwaysMatchesScreen;
@property(retain, nonatomic) PHLocalVideoDisabledOverlayView *disabledOverlayView; // @synthesize disabledOverlayView=_disabledOverlayView;
@property(retain, nonatomic) UIView *localVideoStatusBarGradientView; // @synthesize localVideoStatusBarGradientView=_localVideoStatusBarGradientView;
@property(retain, nonatomic) UIView *localVideoView; // @synthesize localVideoView=_localVideoView;
@property(retain, nonatomic) UIControl *videoGroupView; // @synthesize videoGroupView=_videoGroupView;
- (void).cxx_destruct;
- (unsigned int)supportedInterfaceOrientations;
- (void)_updateLocalPreviewStatusBarGradient;
- (void)_handleVideoPreviewDidStartNotification:(id)arg1;
- (void)_handleLocalCameraAvailableNotification:(id)arg1;
- (void)_handleLocalCameraErrorNotification:(id)arg1;
- (void)_handleOrientationDidChangeNotification:(id)arg1;
- (void)_avFirstPreviewFrameArrived:(id)arg1;
- (void)_ensureLocalVideoWillBecomeVisible;
- (void)_autoFadeInLocalVideo;
- (void)_fadeInLocalVideo;
- (void)stopPreview;
- (void)startPreview;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)updateViewControllerForOrientation:(int)arg1;
- (void)_applyAutoRotationCorrectionForOrientation:(int)arg1 withTransitionCoordinator:(id)arg2;
- (void)_updateLocalVideoOrientationAnimated:(BOOL)arg1;
- (unsigned int)_imAVCameraOrientationForDeviceOrientation:(int)arg1;
- (void)_adjustForOrientationAnimated:(BOOL)arg1;
- (BOOL)_isValidFaceTimeOrientation:(int)arg1;
- (void)_applicationResumed:(id)arg1;
- (void)_applicationSuspended:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)loadView;
- (void)_setupVideoLayers;
- (void)updateLocalVideoToMatchScreen;
- (void)viewDidLayoutSubviews;
- (void)_ensureVideoLayersExist;
- (void)_dissociateVideoLayers;
- (void)associateLocalVideoLayers;
- (void)fadeInAnimated:(BOOL)arg1;
- (void)fadeOutAnimated:(BOOL)arg1;
- (BOOL)shouldDisableEdgeClip;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

