//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PhoneTabViewController.h"

@class NSString;

@interface PhoneViewController : UIViewController <PhoneTabViewController>
{
    float _cachedCellHeight;
    Class _cellClassForCachedCellHeight;
}

+ (BOOL)tabBarIconImageFinished:(id *)arg1 selectedImage:(id *)arg2 forTabBarItemName:(id)arg3;
+ (void)cacheFinishedTabBarIconImage:(id)arg1 finishedSelectedTabBarIconImage:(id)arg2 withTabBarItemName:(id)arg3;
+ (id)defaultPNGName;
+ (id)tabBarIconName;
+ (CDStruct_f8b960e9)badge;
+ (int)tabViewType;
+ (void)initializeIconAndTitle:(id)arg1;
@property(retain, nonatomic) Class cellClassForCachedCellHeight; // @synthesize cellClassForCachedCellHeight=_cellClassForCachedCellHeight;
@property float cachedCellHeight; // @synthesize cachedCellHeight=_cachedCellHeight;
- (void).cxx_destruct;
- (void)_updateCachedCellHeight;
- (void)_prepareForLoadView;
- (void)viewWillUnload;
- (void)contentSizeCategoryDidChange;
- (void)_loadOffsetDefaultForKey:(id)arg1 withScrollView:(id)arg2;
- (void)_saveOffsetDefaultForKey:(id)arg1 withScrollView:(id)arg2;
- (void)savePreferences;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (unsigned int)supportedInterfaceOrientations;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

