//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITabBarControllerDelegate.h"

@class NSString, PHFrecentViewController, PHLocalVideoViewController, PHRegistrationViewController, PhoneContentView, UIViewController<PhoneBaseViewController>, _UIBackdropView;

@interface PhoneRootViewController : UIViewController <UITabBarControllerDelegate>
{
    PhoneContentView *_contentView;
    PHRegistrationViewController *_registrationController;
    PHLocalVideoViewController *_localVideoViewController;
    PHFrecentViewController *_faceTimeRecentViewController;
    BOOL _faceTimeRegistrationViewIsShowing;
    UIViewController<PhoneBaseViewController> *_baseViewController;
    _UIBackdropView *_backdropView;
    UIViewController *_detailsViewController;
}

+ (BOOL)_shouldForwardViewWillTransitionToSize;
@property(retain) UIViewController *detailsViewController; // @synthesize detailsViewController=_detailsViewController;
@property(readonly, retain, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, retain, nonatomic) PHFrecentViewController *faceTimeRecentViewController; // @synthesize faceTimeRecentViewController=_faceTimeRecentViewController;
- (void).cxx_destruct;
- (unsigned int)supportedInterfaceOrientations;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (BOOL)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)destroyFirstRunController;
- (void)showFaceTimeFirstRunViewIfNeeded;
- (void)createFaceTimeFirstRunViewIfNeeded;
- (void)animateInUI;
- (void)ensureBaseViewControllerIsShowing;
- (void)hideDetailsViewController;
- (void)showDetailsViewController;
- (void)hideVideoConferenceBackgroundViewAnimated:(BOOL)arg1;
- (void)showVideoConferenceBackgroundViewAnimated:(BOOL)arg1;
- (void)hideContentViewAnimated:(BOOL)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setContentViewHiddenPosition;
- (void)showContentViewAnimated:(BOOL)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setContentViewNormalPosition;
- (BOOL)isContentViewLoaded;
- (void)setupContentViewFullSize;
- (void)setupContentViewSidebar;
- (float)_contentViewWidthForApplicationBoundsSize:(struct CGSize)arg1;
- (void)_ensureProperPositionForContentView;
- (void)_unloadChildViewControllers;
- (void)_unloadViewsForController:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)_getRotationContentSettings:(CDStruct_3421d26a *)arg1;
- (BOOL)shouldAutorotate;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
@property(readonly, retain, nonatomic) PHLocalVideoViewController *localVideoViewController;
@property(readonly, retain, nonatomic) UIViewController<PhoneBaseViewController> *baseViewController;
- (void)dealloc;
- (void)viewDidUnload;
- (void)loadView;
@property(readonly, retain, nonatomic) PhoneContentView *contentView;
@property(readonly, nonatomic) CDStruct_f8b960e9 applicationBadge;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

