//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

#import "PhoneBaseViewController.h"

@class NSString, PHContactsViewController, PHDialerViewController, PHFavoritesViewController, PHRecentsViewController, PHVoicemailNavigationController, PhoneNavigationController, UINavigationController, UIToolbar;

@interface PhoneTabBarController : UITabBarController <PhoneBaseViewController>
{
    PhoneNavigationController *_favoritesNavigationController;
    PhoneNavigationController *_recentsNavigationController;
    PHFavoritesViewController *_favoritesViewController;
    PHRecentsViewController *_recentsViewController;
    PHContactsViewController *_contactsViewController;
    PHDialerViewController *_dialerViewController;
    PHVoicemailNavigationController *_voicemailViewController;
    BOOL _shouldSwitchToMostRecentViewType;
    UIToolbar *_toolbar;
}

+ (id)defaultPNGName;
+ (int)statusBarStyle;
@property BOOL shouldSwitchToMostRecentViewType; // @synthesize shouldSwitchToMostRecentViewType=_shouldSwitchToMostRecentViewType;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) PHVoicemailNavigationController *voicemailViewController; // @synthesize voicemailViewController=_voicemailViewController;
@property(retain, nonatomic) PHDialerViewController *dialerViewController; // @synthesize dialerViewController=_dialerViewController;
@property(retain, nonatomic) PHContactsViewController *contactsViewController; // @synthesize contactsViewController=_contactsViewController;
@property(retain, nonatomic) PHRecentsViewController *recentsViewController; // @synthesize recentsViewController=_recentsViewController;
@property(retain, nonatomic) PHFavoritesViewController *favoritesViewController; // @synthesize favoritesViewController=_favoritesViewController;
@property(retain, nonatomic) UINavigationController *recentsNavigationController; // @synthesize recentsNavigationController=_recentsNavigationController;
@property(retain, nonatomic) UINavigationController *favoritesNavigationController; // @synthesize favoritesNavigationController=_favoritesNavigationController;
- (void).cxx_destruct;
- (void)_willAppearInRemoteViewController;
- (void)transitionCompleted;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)shouldDisableEdgeClip;
- (id)viewControllerForTabViewType:(int)arg1;
- (int)tabTypeForViewController:(id)arg1;
- (void)handleURL:(id)arg1;
- (BOOL)handleUserActivityContinuation:(id)arg1;
- (void)hideToolbar;
- (void)showToolbarWithItems:(id)arg1;
- (void)switchToTab:(int)arg1;
- (void)_handleVoicemailUIStatusChangedNotification:(id)arg1;
- (int)currentTabViewType;
- (int)defaultTabViewType;
- (void)updateUserActivityState:(id)arg1;
- (void)setSelectedViewController:(id)arg1;
- (void)applicationWillSuspend;
- (void)switchToMostRecentlyUsedTabType;
- (void)applicationDidResume;
- (void)popCurrentNavigationControllerToRootViewControllerIfAppropriate;
- (void)resetViewController;
- (void)cleanUpViewController;
- (void)showFavoritesTab:(BOOL)arg1 recentsTab:(BOOL)arg2 contactsTab:(BOOL)arg3 keypadTab:(BOOL)arg4 voicemailTab:(BOOL)arg5;
- (void)_badgeChanged:(id)arg1;
- (void)_updateAllBadges:(BOOL)arg1;
- (void)registerForBadgeUpdateNotification;
- (void)_stopListeningForBadgeChangedNotifications:(id)arg1;
- (void)_startListeningForBadgeChangedNotifications:(id)arg1;
- (BOOL)_reallyWantsFullScreenLayout;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

