//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PHRecentsHeaderView, UILabel;

@interface PHRecentsMapItemHeaderView : UIView
{
    long _constraintToken;
    UILabel *_titleLabel;
    PHRecentsHeaderView *_headerView;
}

+ (BOOL)requiresConstraintBasedLayout;
@property(retain, nonatomic) PHRecentsHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) long constraintToken; // @synthesize constraintToken=_constraintToken;
- (void).cxx_destruct;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1 call:(id)arg2 title:(id)arg3;

@end

