//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface PHStarkDialerCircleButton : UIButton
{
}

- (void)setImage:(id)arg1 forState:(unsigned int)arg2;
- (void)setHighlighted:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

