//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHStarkGenericDialerViewController.h"

@class UIButton, UIFocusGuide, UIView;

@interface PHStarkInCallKeypadViewController : PHStarkGenericDialerViewController
{
    UIFocusGuide *_leftGuide;
    UIFocusGuide *_rightGuide;
    UIFocusGuide *_topGuide;
    UIFocusGuide *_bottomGuide;
    UIButton *_backButton;
    UIButton *_endButton;
    UIView *_fakeNavigationBar;
}

@property(retain) UIView *fakeNavigationBar; // @synthesize fakeNavigationBar=_fakeNavigationBar;
@property(retain) UIButton *endButton; // @synthesize endButton=_endButton;
@property(retain) UIButton *backButton; // @synthesize backButton=_backButton;
- (void).cxx_destruct;
- (void)hardwareControlEventNotification:(id)arg1;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (id)preferredFocusedItem;
- (void)_moveWithHeading:(unsigned int)arg1;
- (void)postMessageOverlayIfNeeded;
- (void)setLimitedSoftPhoneKeypad:(BOOL)arg1;
- (void)limitedUINotification:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)endButtonTapped:(id)arg1;
- (void)backButtonTapped:(id)arg1;
- (BOOL)shouldUpdateFocusInContext:(id)arg1;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

