//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHStarkGenericTableViewCell.h"

@class CNAvatarView, UILabel;

@interface PHStarkFavoritesTableViewCell : PHStarkGenericTableViewCell
{
    UILabel *_nameLabel;
    UILabel *_phoneNumberTypeLabel;
    CNAvatarView *_contactAvatarView;
}

@property(retain) CNAvatarView *contactAvatarView; // @synthesize contactAvatarView=_contactAvatarView;
@property(retain) UILabel *phoneNumberTypeLabel; // @synthesize phoneNumberTypeLabel=_phoneNumberTypeLabel;
@property(retain) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)setRepresentedFavorite:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

