//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHStarkGenericDialerViewController.h"

@class UIFocusGuide;

@interface PHStarkDialerViewController : PHStarkGenericDialerViewController
{
    UIFocusGuide *_leftGuide;
    UIFocusGuide *_rightGuide;
    UIFocusGuide *_topGuide;
    UIFocusGuide *_bottomGuide;
}

- (void).cxx_destruct;
- (void)hardwareControlEventNotification:(id)arg1;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)_viewControllerWasSelected;
- (void)highlightControlAtIndex:(int)arg1;
- (void)_moveWithHeading:(unsigned int)arg1;
- (void)deleteButtonHide:(id)arg1;
- (void)postMessageOverlayIfNeeded;
- (void)setLimitedSoftPhoneKeypad:(BOOL)arg1;
- (void)limitedUINotification:(id)arg1;
- (BOOL)shouldUpdateFocusInContext:(id)arg1;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (id)preferredFocusedItem;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

