//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHStarkGenericViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AVExternalDevice, NSString, PHStarkNoContentBannerView, UITableView, _UIFilteredDataSource;

@interface PHStarkGenericTableViewController : PHStarkGenericViewController <UITableViewDataSource, UITableViewDelegate>
{
    BOOL _tableViewReloadIsRequiredOnViewWillAppear;
    UITableView *_mainTableView;
    _UIFilteredDataSource *_mainTableViewDataSource;
    PHStarkNoContentBannerView *_noContentBannerView;
    AVExternalDevice *_carPlayExternalDevice;
}

@property(retain) AVExternalDevice *carPlayExternalDevice; // @synthesize carPlayExternalDevice=_carPlayExternalDevice;
@property(retain) PHStarkNoContentBannerView *noContentBannerView; // @synthesize noContentBannerView=_noContentBannerView;
@property BOOL tableViewReloadIsRequiredOnViewWillAppear; // @synthesize tableViewReloadIsRequiredOnViewWillAppear=_tableViewReloadIsRequiredOnViewWillAppear;
@property(retain) _UIFilteredDataSource *mainTableViewDataSource; // @synthesize mainTableViewDataSource=_mainTableViewDataSource;
@property(retain) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
- (void).cxx_destruct;
- (BOOL)_viewControllerWasSelected;
- (void)limitedUIChanged:(id)arg1;
- (int)filterType;
- (void)starkInCallViewControllerAppearedNotification:(id)arg1;
- (void)updateBadgeString;
@property(readonly) NSString *badgeString;
- (id)subtitleForNoContentBanner;
- (id)titleForNoContentBanner;
- (void)setNoContentBannerShown:(BOOL)arg1;
- (void)hardwareControlEventNotification:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)preferredFocusedItem;
- (void)programmaticallySelectRowAtIndexPath:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (float)defaultRowHeight;
- (void)loadView;
- (void)applicationBadgeChangedNotification:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

