//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PHUIConfiguration : NSObject
{
}

+ (unsigned int)voicemailLayoutSpacing;
+ (unsigned int)tableViewCellVerticalSpacing;
+ (BOOL)shouldUseFullScreenPeoplePicker;
+ (unsigned int)pipStatusBarPadding;
+ (float)pipWallInset;
+ (float)pipWidth;
+ (float)bottomOffsetForFaceTimeUIInLandscapeMode;
+ (float)topOffsetForFaceTimeUIInLandscapeMode;
+ (unsigned int)contentViewSizeForFaceTime;
+ (BOOL)canRotateInCallUIOverlayForFaceTime;
+ (BOOL)canAutoRotateInCallUIForFaceTimeAudio;
+ (BOOL)canAutoRotateInCallUIForFaceTime;
+ (unsigned int)handsetDialerSize;
+ (unsigned int)handsetDialerSpacing;
+ (BOOL)inCallBarsMakeSpaceForContent;
+ (unsigned int)inCallControlSize;
+ (unsigned int)inCallBottomBarSpacing;
+ (unsigned int)inCallControlSpacing;
+ (unsigned int)inCallControlAlignment;
+ (unsigned int)screenSize;
+ (id)dialerColor;
+ (float)dialerLCDLabelFontSizeInCall;
+ (float)dialerLCDLabelFontSize;
+ (float)dialerLCDFontSizeInCall;
+ (float)dialerLCDFontSize;

@end

