//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, AVPlayer, AVPlayerItem;

@interface PHVoicemailPlayerController : NSObject
{
    BOOL _interrupted;
    int _status;
    id <NSObject> _didStart;
    id <NSObject> _didEnd;
    id <NSObject> _timeObserver;
    AVPlayer *_audioPlayer;
    AVPlayerItem *_playerItem;
    CDStruct_1b6d18a9 _duration;
}

+ (id)sharedPlayerController;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) AVPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(retain, nonatomic) id <NSObject> timeObserver; // @synthesize timeObserver=_timeObserver;
@property(retain, nonatomic) id <NSObject> didEnd; // @synthesize didEnd=_didEnd;
@property(retain, nonatomic) id <NSObject> didStart; // @synthesize didStart=_didStart;
@property(nonatomic) BOOL interrupted; // @synthesize interrupted=_interrupted;
@property(nonatomic) CDStruct_1b6d18a9 duration; // @synthesize duration=_duration;
@property(nonatomic) int status; // @synthesize status=_status;
- (void).cxx_destruct;
@property(readonly, nonatomic) AVAsset *currentAsset;
- (void)currentAssetDurationWithBlock:(CDUnknownBlockType)arg1;
- (CDStruct_1b6d18a9)currentTime;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
- (void)pause;
- (void)play;
- (void)loadAudio:(id)arg1 withObserverForInterval:(CDStruct_1b6d18a9)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)_createAVPlayer;
- (BOOL)endInterruption;
- (BOOL)beginInterruption;
- (BOOL)isPlaying;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)resetAudioPlayer;
- (void)dealloc;

@end

