//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHVoicemailListViewController.h"

#import "PHVoicemailListViewControllerConcrete.h"
#import "UIActionSheetDelegate.h"

@class NSArray, NSString, UIActionSheet;

@interface PHVoicemailBlockedListViewController : PHVoicemailListViewController <UIActionSheetDelegate, PHVoicemailListViewControllerConcrete>
{
    UIActionSheet *_deleteAllConfirmationActionSheet;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)deleteAllTapped;
@property(readonly) BOOL popOffIfEmpty;
- (void)performCellDetailDestructiveActionForVoicemail:(id)arg1;
@property(readonly) NSString *cellDetailDestructiveActionText;
- (void)performTableViewDestructiveActionForVoicemail:(id)arg1;
@property(readonly) NSString *tableViewDestructiveActionText;
@property(readonly) unsigned int flagsNotToHave;
@property(readonly) unsigned int flagsToHave;
@property(readonly) NSString *folderName;
@property(readonly) NSString *navigationBarText;
- (id)initWithNavigationController:(id)arg1;

// Remaining properties
@property(readonly) NSArray *childListControllers;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) NSString *navigationBarTextWithCountFormat;
@property(readonly) Class superclass;

@end

