//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "MPDetailSliderDelegate.h"

@class NSString, PHVoicemailSlider, UIProgressView;

@interface PHVoicemailGreetingSliderCell : UITableViewCell <MPDetailSliderDelegate>
{
    UIProgressView *_progressView;
    PHVoicemailSlider *_slider;
}

@property(retain, nonatomic) PHVoicemailSlider *slider; // @synthesize slider=_slider;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (void)detailSliderTrackingDidCancel:(id)arg1;
- (void)detailSliderTrackingDidEnd:(id)arg1;
- (void)showProgressView;
- (void)showSlider;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

