//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "PHVoicemailGreetingModelDelegate.h"
#import "PHVoicemailGreetingPlaybackCellDelegate.h"

@class NSString, PHVoicemailGreetingModel;

@interface PHVoicemailGreetingViewController : UITableViewController <PHVoicemailGreetingPlaybackCellDelegate, PHVoicemailGreetingModelDelegate>
{
    BOOL _presentedFromSetup;
    BOOL _hasRecordedNewGreeting;
    id <PHVoicemailGreetingViewControllerDelegate> _greetingDelegate;
    PHVoicemailGreetingModel *_greetingModel;
}

@property(retain, nonatomic) PHVoicemailGreetingModel *greetingModel; // @synthesize greetingModel=_greetingModel;
@property(nonatomic) BOOL hasRecordedNewGreeting; // @synthesize hasRecordedNewGreeting=_hasRecordedNewGreeting;
@property id <PHVoicemailGreetingViewControllerDelegate> greetingDelegate; // @synthesize greetingDelegate=_greetingDelegate;
@property(getter=isPresentedFromSetup) BOOL presentedFromSetup; // @synthesize presentedFromSetup=_presentedFromSetup;
- (void).cxx_destruct;
- (void)voicemailGreetingDidFinishRecording;
- (void)voicemailGreetingDurationChanged:(double)arg1;
- (void)voicemailGreetingRecordingProgressChanged:(float)arg1;
- (void)voicemailGreetingFailedWithError:(id)arg1;
- (void)voicemailGreetingPlayingProgressChanged:(float)arg1;
- (void)voicemailGreetingAudioControllerDidChangeState:(int)arg1;
- (void)_selectCell:(id)arg1;
- (void)voicemailGreetingDidSave;
- (void)recordStopButtonTapped;
- (void)playStopButtonTapped;
- (void)_saveButtonTapped;
- (void)_cancelButtonTapped;
- (id)_selectedCellIndexPath;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)_titleForCellAtIndexPath:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)playbackControlsCell;
- (id)sliderCell;
- (void)_handleDeactivation:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

