//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHAudioRecorderDelegate.h"

@class NSTimer, PHAudioRecorder;

@interface PHVoicemailGreetingModel : NSObject <PHAudioRecorderDelegate>
{
    id <PHVoicemailGreetingModelDelegate> _delegate;
    int _greetingState;
    PHAudioRecorder *_greetingRecorder;
    NSTimer *_greetingFetchTimeoutTimer;
    NSTimer *_greetingSaveTimeoutTimer;
    double _greetingDuration;
}

@property(retain, nonatomic) NSTimer *greetingSaveTimeoutTimer; // @synthesize greetingSaveTimeoutTimer=_greetingSaveTimeoutTimer;
@property(retain, nonatomic) NSTimer *greetingFetchTimeoutTimer; // @synthesize greetingFetchTimeoutTimer=_greetingFetchTimeoutTimer;
@property(nonatomic) double greetingDuration; // @synthesize greetingDuration=_greetingDuration;
@property(retain, nonatomic) PHAudioRecorder *greetingRecorder; // @synthesize greetingRecorder=_greetingRecorder;
@property(nonatomic) int greetingState; // @synthesize greetingState=_greetingState;
@property(nonatomic) __weak id <PHVoicemailGreetingModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_stopListeningForGreetingSaveNotifications;
- (void)_stopListeningForGreetingFetchNotifications;
- (id)greetingTempFileLocation;
- (void)_greetingSaveTimedOut;
- (void)_greetingSaveCompleted:(id)arg1;
- (void)_greetingFetchTimedOut;
- (void)_greetingFetchEnded:(id)arg1;
- (void)audioRecorderEndedWithFile:(id)arg1 duration:(double)arg2 error:(id)arg3;
- (void)audioRecorderContinuedWithFile:(id)arg1 duration:(double)arg2;
- (void)audioRecorderStartedWithFile:(id)arg1;
- (void)_handlePlayerDidFinishPlaying:(id)arg1;
- (void)_handlePlayerControllerRateOrStatusChange:(id)arg1;
- (void)fetchGreeting;
- (void)saveGreeting:(int)arg1 useServerCachedGreeting:(BOOL)arg2;
- (void)saveGreeting:(int)arg1;
- (void)pauseGreeting;
- (void)playGreeting;
- (void)_mediaserverReset:(id)arg1;
- (void)_loadGreeting:(id)arg1;
- (void)stopRecording;
- (void)startRecording;
- (int)mailboxGreetingState;
- (void)dealloc;
- (id)init;

@end

