//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHVoicemailListViewController.h"

#import "PHVoicemailGreetingViewControllerDelegate.h"
#import "PHVoicemailListViewControllerConcrete.h"

@class NSArray, NSString, UIBarButtonItem, _UIContentUnavailableView;

@interface PHVoicemailInboxListViewController : PHVoicemailListViewController <PHVoicemailGreetingViewControllerDelegate, PHVoicemailListViewControllerConcrete>
{
    BOOL _isSwipeToDelete;
    UIBarButtonItem *_readButton;
    UIBarButtonItem *_deleteButton;
    _UIContentUnavailableView *_noContentView;
}

@property(retain, nonatomic) _UIContentUnavailableView *noContentView; // @synthesize noContentView=_noContentView;
@property(retain, nonatomic) UIBarButtonItem *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIBarButtonItem *readButton; // @synthesize readButton=_readButton;
@property(nonatomic) BOOL isSwipeToDelete; // @synthesize isSwipeToDelete=_isSwipeToDelete;
- (void).cxx_destruct;
- (void)_delete:(id)arg1;
- (void)_markAsRead:(id)arg1;
- (BOOL)_selectionContainsUnreadVoicemail;
- (void)_updateGreetingButtonAllowed;
- (void)voicemailGreetingViewControllerFinished:(id)arg1;
- (void)greetingButtonTapped;
- (void)willShowVoicemails:(id)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
@property(readonly) BOOL popOffIfEmpty;
- (void)performCellDetailDestructiveActionForVoicemail:(id)arg1;
@property(readonly) NSString *cellDetailDestructiveActionText;
- (void)performTableViewDestructiveActionForVoicemail:(id)arg1;
@property(readonly) NSString *tableViewDestructiveActionText;
@property(readonly) NSArray *childListControllers;
@property(readonly) unsigned int flagsNotToHave;
@property(readonly) unsigned int flagsToHave;
@property(readonly) NSString *navigationBarTextWithCountFormat;
@property(readonly) NSString *folderName;
@property(readonly) NSString *navigationBarText;
- (void)dealloc;
- (id)initWithNavigationController:(id)arg1;

@end

