//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneViewController.h"

#import "CNAvatarCardControllerDelegate.h"
#import "CNContactViewControllerDelegate.h"
#import "PHVoicemailCellDelegate.h"
#import "PHVoicemailListMaskViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CNAvatarCardController, NSArray, NSIndexPath, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSString, PHVoicemailListMaskView, PHVoicemailNavigationController, UIGestureRecognizer, UITableView, VMVoicemail;

@interface PHVoicemailListViewController : PhoneViewController <PHVoicemailListMaskViewDelegate, CNContactViewControllerDelegate, UIGestureRecognizerDelegate, PHVoicemailCellDelegate, CNAvatarCardControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    PHVoicemailNavigationController *_navigationController;
    PHVoicemailListMaskView *_maskView;
    NSObject<OS_dispatch_queue> *_queue;
    int _disableUserInteractionCountLock;
    int _disableUserInteractionCount;
    int _isReloadingTableViewLock;
    BOOL _isReloadingTableView;
    BOOL _shouldReloadTableView;
    NSObject<OS_dispatch_queue> *_initialSetupQueue;
    int _isSettingUpLock;
    BOOL _isSettingUp;
    BOOL _reloadAfterInitialSetup;
    NSObject<OS_dispatch_group> *_loadingGroup;
    NSArray *_voicemails;
    NSArray *_childListViewControllersWithContent;
    BOOL _showingUnavailableCell;
    BOOL _visible;
    NSIndexPath *_detailIndexPath;
    VMVoicemail *_selectedVoicemail;
    UIGestureRecognizer *_navBarGestureRecognizer;
    UIGestureRecognizer *_leftBarButtonItemGestureRecognizer;
    UIGestureRecognizer *_rightBarButtonItemGestureRecognizer;
    CNAvatarCardController *_cardController;
}

@property(retain, nonatomic) CNAvatarCardController *cardController; // @synthesize cardController=_cardController;
@property(retain) UIGestureRecognizer *rightBarButtonItemGestureRecognizer; // @synthesize rightBarButtonItemGestureRecognizer=_rightBarButtonItemGestureRecognizer;
@property(retain) UIGestureRecognizer *leftBarButtonItemGestureRecognizer; // @synthesize leftBarButtonItemGestureRecognizer=_leftBarButtonItemGestureRecognizer;
@property(retain) UIGestureRecognizer *navBarGestureRecognizer; // @synthesize navBarGestureRecognizer=_navBarGestureRecognizer;
@property(retain) NSArray *childListViewControllersWithContent; // @synthesize childListViewControllersWithContent=_childListViewControllersWithContent;
@property(retain) VMVoicemail *selectedVoicemail; // @synthesize selectedVoicemail=_selectedVoicemail;
@property(retain) NSIndexPath *detailIndexPath; // @synthesize detailIndexPath=_detailIndexPath;
@property BOOL visible; // @synthesize visible=_visible;
@property BOOL showingUnavailableCell; // @synthesize showingUnavailableCell=_showingUnavailableCell;
@property(retain) NSArray *voicemails; // @synthesize voicemails=_voicemails;
@property PHVoicemailNavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;
- (int)avatarCardController:(id)arg1 presentationResultForLocation:(struct CGPoint)arg2;
- (id)presentingViewControllerForAvatarCardController:(id)arg1;
- (id)unknownContactForVoicemail:(id)arg1;
- (void)_updateUIForMaskViewChange;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_handleNavBarTap:(id)arg1;
- (void)_enableInteraction;
- (void)_disableInteraction;
- (void)_reloadTableViewIfNecessary;
- (void)_performEfficientTableViewReloadWithVoicemails:(id)arg1 childListControllersWithContent:(id)arg2 showingUnavailableCell:(BOOL)arg3;
- (void)_forceCompleteTableViewReloadWithVoicemails:(id)arg1 childListControllersWithContent:(id)arg2 showingUnavailableCell:(BOOL)arg3;
- (void)_popOffIfNeeded;
- (id)_indexPathForItem:(id)arg1 inList:(id)arg2 offset:(int)arg3;
- (id)_indexPathsForItems:(id)arg1 inList:(id)arg2 offset:(int)arg3;
- (void)_updateTitle;
- (int)_firstVoicemailOffset;
- (void)exportVoicemailDataForVoicemail:(id)arg1;
- (void)closeVoicemail;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (void)maskViewWasTappedOutsideOfShownCell:(id)arg1;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (float)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (id)contentScrollView;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
@property(readonly) BOOL shouldBeShown;
- (id)_fetchCurrentChildListViewControllersWithContent;
- (id)_fetchCurrentVoicemails;
- (id)_allVoicemails;
- (void)_voicemailUnavailableCellHeightChanged:(id)arg1;
- (void)_handleContentSizeDidChange:(id)arg1;
- (void)_reloadVoicemailUI;
- (void)_handleSignificantTimeChange:(id)arg1;
- (void)_handleBackgroundNotification:(id)arg1;
- (void)_handleVoicemailListChanged:(id)arg1;
- (void)playVoicemail:(id)arg1;
- (void)forceReloadIfNecessary;
- (void)dealloc;
- (id)initWithNavigationController:(id)arg1;
- (id)table;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

