//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (PHInCallUIUtilities)
- (float)yOriginForCenterOfSuperview;
- (float)xOriginForCenterOfSuperview;
- (struct CGAffineTransform)transformToAbutToEdge:(unsigned int)arg1 ofView:(id)arg2;
@end

